(function(){
 const roles=[
 ['UNITY-04','UNITY','GAMEPLAY','baking arena navigation','SCENE / ARENA_07','73'],['BLENDER-11','BLENDER','3D ASSET','rigging mech hunter','ARMATURE / 128 BONES','61'],['SOLANA-07','ANCHOR','CONTRACT','testing item ownership','PROGRAM / ITEM_CORE','86'],['ECONOMY-03','SIMULATOR','ECONOMY','simulating season emissions','MODEL / SEASON_01','48'],['AUDITOR-02','SECURITY','AUDIT','scanning program authorities','INVARIANTS / 4 OF 5','80'],['PC-BUILD-06','WINDOWS','PLATFORM','profiling combat frame','BUILD / WIN64_0184','92'],['ANDROID-03','ANDROID','PLATFORM','running device build','PIXEL 9 / 58 FPS','67'],['IOS-08','XCODE','PLATFORM','signing simulator build','IOS / SIMULATOR','55'],['QA-09','PLAYTEST','QUALITY','running encounter 047','RUN / NO DEATHS','39'],['WORLD-05','UNITY','WORLD','assembling sector delta','SCENE / DELTA_12','76'],['VFX-12','BLENDER','VFX','rendering impact particles','CACHE / 240 FRAMES','44'],['INTEGRATOR-01','GIT + CI','MERGE','merging verified outputs','NEXT / BUILD_0185','68']];
 const marks=['U','B','S','E','Σ','P','A','I','Q','W','V','M'];
 const logs=[['navmesh tiles accepted','enemy state graph compiled','play mode test passed'],['mesh topology clean','animation retarget complete','exported glb artifact'],['local validator online','ownership tests passing','compute units measured'],['sink ratio stable','reward curve sampled','inflation bound verified'],['upgrade authority checked','signer boundary traced','one invariant pending'],['shader warmup complete','frame pacing sampled','package checksum signed'],['gradle task running','vulkan frame captured','device smoke test passed'],['xcode archive prepared','entitlements checked','simulator boot verified'],['combat route selected','collision edge reproduced','telemetry frame saved'],['terrain cells stitched','spawn volumes rebuilt','lighting probe baked'],['particle cache baking','material pass linked','impact timing sampled'],['artifact hashes matched','platform gates checked','candidate merge staged']];
 const visual=i=>i===0?`<div class='unity-scene'><i></i><i></i><b></b></div>`:i===1||i===10?`<div class='mesh-orb'><i></i><b></b><em></em></div>`:i===2?`<div class='contract-code'><i>pub fn mint_item(ctx)</i><i>require!(authority)</i><i>emit!(ItemCreated)</i><i>Ok(())</i></div>`:i===3?`<div class='economy-bars'><i></i><i></i><i></i><i></i><i></i><i></i></div>`:i===4?`<div class='audit-list'><i>✓ OWNER</i><i>✓ SIGNER</i><i>✓ SUPPLY</i><i>… UPGRADE</i></div>`:i===6||i===7?`<div class='device-frame'><i></i><b>${i===6?'ANDROID':'iOS'}</b><em>BUILD LIVE</em></div>`:i===8?`<div class='playtest-frame'><i></i><b>ENCOUNTER 047</b><em>HP 084 / FPS 60</em></div>`:i===9?`<div class='world-map'><i></i><i></i><i></i><i></i><b>SECTOR Δ</b></div>`:i===11?`<div class='merge-tree'><i></i><i></i><i></i><b></b></div>`:`<div class='perf-chart'><i></i><b>16.7ms</b><em>GPU 71%</em></div>`;
 function mount(){const wall=document.querySelector('.machine-wall');if(!wall)return;if(wall.children.length===12&&wall.firstElementChild?.classList.contains('game-agent'))return;
  wall.className='machine-wall game-agent-wall twelve';
  wall.innerHTML=roles.map((r,i)=>`<article class='game-agent role-${i}' tabindex='0'><header><span><i></i>${String(i+1).padStart(2,'0')} / ${r[0]}</span><b>LIVE</b></header><div class='agent-tool'><div class='tool-title'><b>${r[1]}</b><span>${r[2]}</span><em>${r[4]}</em></div><div class='tool-viewport'>${visual(i)}<span class='agent-cursor'>${marks[i]}</span><div class='tool-scan'></div></div><div class='agent-console'><p><i>›</i><span>${logs[i][0]}</span></p><p><i>›</i><span>${logs[i][1]}</span></p><p><i>›</i><span>${logs[i][2]}</span></p></div></div><footer><span>${r[3]}</span><b><i style='--p:${r[5]}%'></i></b><em>${r[5]}%</em></footer></article>`).join('');
  wall.querySelectorAll('.game-agent').forEach((card,i)=>{const data=window.VEEMO_STATE?.agents?.[roles[i][0]]||{status:'offline',task:'worker not connected',detail:'no verified output',proof:'—'};card.dataset.status=data.status;card.querySelector('header>b').textContent=data.status.toUpperCase();card.querySelector('footer>span').textContent=data.task;card.querySelector('footer>em').textContent=data.status==='complete'?'100%':'—';card.querySelector('footer>b>i').style.setProperty('--p',data.status==='complete'?'100%':'0%');const lines=card.querySelectorAll('.agent-console span');lines[0].textContent=data.task;lines[1].textContent=data.detail||'no worker telemetry';lines[2].textContent='proof / '+(data.proof||'none')});
  const command=document.querySelector('.machine-command');if(command){const b=command.querySelector('b'),e=command.querySelector('em'),buttons=command.querySelectorAll('nav button');if(b)b.textContent='agent workstreams --verified-output';if(e)e.textContent='# real worker state · click an agent to inspect';if(buttons[2])buttons[2].textContent='[a]gents 12';if(buttons[5])buttons[5].textContent='[l]ive 5';if(buttons[6])buttons[6].textContent='[o]ffline 7'}
  wall.querySelectorAll('.game-agent').forEach((card,i)=>{const open=()=>{localStorage.setItem('veemo.focus',roles[i][0]);location.hash='live';location.reload()};card.addEventListener('click',open);card.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();open()}})});
 }
 setInterval(mount,2000);
 const target=document.querySelector('.machine-wall');if(target)new MutationObserver(()=>setTimeout(mount,0)).observe(target,{childList:true});setTimeout(mount,500);
})();
