(function(){
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const state={route:'live',task:'allocator',connected:false};
  const tasks={allocator:{id:'M-7F3A',path:'runtime/allocator.rs',machine:'helix-17'},merkle:{id:'M-82C1',path:'kernels/merkle.cu',machine:'cobalt-03'},parser:{id:'M-91D0',path:'codec/parser.zig',machine:'kiln-22'},vm:{id:'M-A033',path:'vm/vm_exec.rs',machine:'vector-08'},codec:{id:'M-B812',path:'transport/codec.ts',machine:'oxide-11'}};
  const snippets={
    diff:'<ol><li><code>pub fn reserve(&amp;mut self, requested: usize) {</code></li><li class="minus"><code>let next = self.cursor + requested;</code></li><li class="minus"><code>if next &gt; self.capacity {</code></li><li class="minus"><code>self.grow(next);</code></li><li class="minus"><code>}</code></li><li class="plus"><code>let aligned = requested.next_multiple_of(64);</code></li><li class="plus"><code>let next = self.cursor.saturating_add(aligned);</code></li><li class="plus"><code>if unlikely(next &gt; self.capacity) {</code></li><li class="plus"><code>self.grow(next.next_power_of_two());</code></li><li class="plus"><code>}</code></li><li><code>self.cursor = next;</code></li><li><code>}</code></li></ol><span class="compile-scan"></span>',
    source:'<ol><li><code>#[inline(always)]</code></li><li><code>pub fn reserve(&amp;mut self, requested: usize) {</code></li><li><code>let aligned = requested.next_multiple_of(64);</code></li><li><code>let next = self.cursor.saturating_add(aligned);</code></li><li><code>if unlikely(next &gt; self.capacity) {</code></li><li><code>self.grow(next.next_power_of_two());</code></li><li><code>}</code></li><li><code>self.cursor = next;</code></li><li><code>}</code></li></ol>',
    assembly:'<ol><li><code>push   %rbp</code></li><li><code>mov    %rsp,%rbp</code></li><li><code>add    $0x3f,%rsi</code></li><li><code>and    $0xffffffffffffffc0,%rsi</code></li><li><code>add    0x18(%rdi),%rsi</code></li><li><code>jb     0x0000000000413f20</code></li><li><code>cmp    0x20(%rdi),%rsi</code></li><li><code>ja     0x0000000000413f20</code></li><li><code>mov    %rsi,0x18(%rdi)</code></li><li><code>pop    %rbp</code></li><li><code>ret</code></li></ol>'
  };
  function route(next){if(!document.querySelector('[data-view="'+next+'"]'))next='live';state.route=next;$$('.app-view').forEach(v=>v.classList.toggle('is-active',v.dataset.view===next));$$('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===next));const detail=$('#landingDetail');if(detail)detail.hidden=next!=='live';document.body.dataset.route=next;scrollTo(0,0)}
  function fromHash(){route(location.hash.slice(1)||'live')}
  $$('[data-route]').forEach(a=>a.addEventListener('click',e=>{const r=a.dataset.route;if(!r)return;e.preventDefault();history.pushState(null,'','#'+r);route(r)}));addEventListener('popstate',fromHash);fromHash();
  const nums=$$('[data-count]'),reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;nums.forEach(el=>{const end=Number(el.dataset.count),suffix=el.dataset.suffix||'',dec=String(end).includes('.');if(reduce){el.textContent=(dec?end.toFixed(1):end.toLocaleString())+suffix;return}let start=performance.now();function tick(now){let p=Math.min(1,(now-start)/1200),v=end*(1-Math.pow(1-p,3));el.textContent=(dec?v.toFixed(1):Math.round(v).toLocaleString())+suffix;if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)});
  const etClock=()=>new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(new Date());function clock(){const el=$('#clock');if(el)el.textContent=etClock()+' ET'}clock();setInterval(clock,1000);
  function copied(btn,value){navigator.clipboard?.writeText(value);const old=btn.textContent;btn.textContent='copied';setTimeout(()=>btn.textContent=old,1200)}$$('[data-copy]').forEach(btn=>btn.addEventListener('click',()=>copied(btn,btn.dataset.copy)));
  $$('.pane-title button').forEach(b=>b.addEventListener('click',()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}));
  $$('.queue-item').forEach(item=>item.addEventListener('click',()=>{state.task=item.dataset.task;$$('.queue-item').forEach(x=>x.classList.remove('selected'));item.classList.add('selected');const t=tasks[state.task];$('#editorPath').textContent=t.path;$('#editorMutation').textContent=t.id;$('.editor-meta span:nth-child(3) b').textContent=t.machine;$('#fullCode').animate([{opacity:.25},{opacity:1}],{duration:260});}));
  $$('[data-editor-tab]').forEach(btn=>btn.addEventListener('click',()=>{$$('[data-editor-tab]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$('#fullCode').innerHTML=snippets[btn.dataset.editorTab];}));
  // Pump.fun actions point directly to the live $VEEMO market.
  // X uses its real external href; do not intercept navigation.
  const socialX=$('[data-social]');if(socialX){socialX.href='https://x.com/veemonsol';socialX.title='Veemo on X';socialX.setAttribute('aria-label','Veemo on X');socialX.innerHTML='<svg class="official-x-mark" viewBox="0 0 24 24" aria-hidden="true"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231 5.451-6.231Zm-1.161 17.52h1.833L7.084 4.126H5.117L17.083 19.77Z"/></svg>'}
  const pumpLinks=$$('[data-pump]');pumpLinks.forEach(pumpLink=>{pumpLink.href='https://pump.fun/coin/CcSchh9dGiZ8y1aVTBiAvPtmqqnFRnSx2ZazT641pump';pumpLink.title='Buy $VEEMO';pumpLink.setAttribute('aria-label','Buy $VEEMO on Pump.fun')});

  const modal=$('#walletModal');function modalOpen(){modal.classList.add('open');modal.setAttribute('aria-hidden','false')}function modalClose(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}$('.header-actions button')?.addEventListener('click',modalOpen);$('.modal-close')?.addEventListener('click',modalClose);modal?.addEventListener('click',e=>{if(e.target===modal)modalClose()});addEventListener('keydown',e=>{if(e.key==='Escape')modalClose()});$$('.wallet-choice').forEach(btn=>btn.addEventListener('click',()=>{state.connected=true;$('.header-actions button').textContent='8Kr…p21';$$('.wallet-choice b').forEach(b=>b.textContent='available');$('b',btn).textContent='connected ✓';setTimeout(modalClose,500)}));
  const cpu=$('#cpuRange'),mem=$('#memRange'),name=$('#machineName'),target=$('#machineTarget');function preview(){if(cpu){$('#cpuOut').textContent=cpu.value;$('#previewCpu').textContent=cpu.value+' vCPU'}if(mem){$('#memOut').textContent=mem.value+' GB';$('#previewMem').textContent=mem.value+' GB'}if(name)$('#previewName').textContent=name.value||'unnamed-machine';if(target)$('#previewClass').textContent=target.value.split('/').map(x=>x.trim().toUpperCase()).join(' / ')};[cpu,mem,name,target].filter(Boolean).forEach(x=>x.addEventListener('input',preview));preview();
  $('#spawnForm')?.addEventListener('submit',e=>{e.preventDefault();const btn=$('.spawn-submit');if(!$('#attest').checked){btn.textContent='confirm verifier attestation first';btn.classList.add('warning');setTimeout(()=>{btn.textContent='connect wallet & attest machine';btn.classList.remove('warning')},1800);return}if(!state.connected){modalOpen();return}btn.textContent='machine attestation prepared ✓'});
  $$('.treasury-ledger .subhead button').forEach(btn=>btn.addEventListener('click',()=>{$$('.treasury-ledger .subhead button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const f=btn.textContent.trim();$$('.treasury-ledger .ledger-row:not(.head)').forEach(row=>{const kind=$('.kind',row)?.textContent.trim()||'';row.style.display=f==='all'||kind.includes(f)?'grid':'none'})}));
})();
