#!/usr/bin/env node
import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, openSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
const root=resolve(import.meta.dirname),agentsRoot=join(root,'agents'),pidsFile=join(agentsRoot,'pids.json'),server=process.env.VEEMO_SERVER||'http://127.0.0.1:4210';
const fleet=[{name:'helix-01',target:'bitcoin / p2p',repo:'bitcoin/bitcoin'},{name:'vector-02',target:'ethereum / evm',repo:'ethereum/go-ethereum'},{name:'kiln-03',target:'transformers / inference',repo:'huggingface/transformers'},{name:'cobalt-04',target:'openai / sdk',repo:'openai/openai-python'},{name:'orbit-05',target:'solana / runtime',repo:'anza-xyz/agave'},{name:'tensor-06',target:'pytorch / tensors',repo:'pytorch/pytorch'},{name:'matrix-07',target:'tensorflow / kernels',repo:'tensorflow/tensorflow'},{name:'beacon-08',target:'langchain / agents',repo:'langchain-ai/langchain'}];
const command=process.argv[2]||'status';mkdirSync(agentsRoot,{recursive:true});
function envValue(name){const path=join(root,'.env');if(!existsSync(path))return '';const line=readFileSync(path,'utf8').split(/\r?\n/).find(item=>item.startsWith(`${name}=`));return line?line.slice(name.length+1):''}
async function api(path,options={}){const response=await fetch(server+path,{headers:{'content-type':'application/json',...(options.headers||{})},...options}),value=await response.json();if(!response.ok)throw new Error(value.error||`HTTP ${response.status}`);return value}
function alive(pid){try{process.kill(pid,0);return true}catch{return false}}
if(command==='bootstrap'){const key=envValue('VEEMO_REGISTRATION_KEY');if(!key)throw new Error('VEEMO_REGISTRATION_KEY missing from .env');const state=await api('/api/state');for(const agent of fleet){const directory=join(agentsRoot,agent.name),configPath=join(directory,'.veemo-worker.json');mkdirSync(directory,{recursive:true});const existing=state.machines.find(machine=>machine.name===agent.name);if(existing&&existsSync(configPath)){console.log(`${agent.name}: already registered`);continue}if(existing)throw new Error(`${agent.name} exists on core but local credential is missing`);const result=await api('/api/machines/register',{method:'POST',body:JSON.stringify({name:agent.name,target:agent.target,cpu:2,memoryGb:4,registrationKey:key})});writeFileSync(configPath,JSON.stringify({server,machine:result.machine,secret:result.secret},null,2),{mode:0o600});console.log(`${agent.name}: ${result.machine.id}`)}}
else if(command==='start'){if(existsSync(pidsFile)){const old=JSON.parse(readFileSync(pidsFile,'utf8'));if(old.some(item=>alive(item.pid)))throw new Error('fleet is already running')}const children=[];for(const agent of fleet){const directory=join(agentsRoot,agent.name),config=join(directory,'.veemo-worker.json');if(!existsSync(config))throw new Error(`${agent.name} is not bootstrapped`);const log=openSync(join(directory,'agent.log'),'a'),child=spawn(process.execPath,[join(root,'worker.mjs'),'start','--auto'],{cwd:directory,stdio:['ignore',log,log],windowsHide:true,env:{...process.env,VEEMO_ACTIVITY:`scanning ${agent.repo}`}});children.push({name:agent.name,pid:child.pid,child});console.log(`${agent.name}: started pid ${child.pid}`)}writeFileSync(pidsFile,JSON.stringify(children.map(({name,pid})=>({name,pid})),null,2));const shutdown=()=>{for(const item of children)if(alive(item.pid))item.child.kill();process.exit(0)};process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown);setInterval(()=>{},60000)}
else if(command==='stop'){if(!existsSync(pidsFile)){console.log('fleet is not running');process.exit(0)}for(const item of JSON.parse(readFileSync(pidsFile,'utf8'))){if(alive(item.pid)){process.kill(item.pid);console.log(`${item.name}: stopped`)}else console.log(`${item.name}: already stopped`)}writeFileSync(pidsFile,'[]')}
else if(command==='status'){const state=await api('/api/state');for(const agent of fleet){const machine=state.machines.find(item=>item.name===agent.name);console.log(`${agent.name.padEnd(12)} ${machine?.status||'not registered'} ${machine?.id||''}`)}}
else console.log('usage: node fleet.mjs bootstrap|start|stop|status');