(function(){
 const state=window.VEEMO_STATE||{updatedAt:null,agents:{}};
 const roles=['UNITY-04','BLENDER-11','SOLANA-07','ECONOMY-03','AUDITOR-02','PC-BUILD-06','ANDROID-03','IOS-08','QA-09','WORLD-05','VFX-12','INTEGRATOR-01'];
 const focus=localStorage.getItem('veemo.focus')||'BLENDER-11';
 const data=state.agents[focus]||{status:'offline',task:'worker not connected',detail:'no verified telemetry',proof:'none',artifact:'no artifact'};
 const q=s=>document.querySelector(s);
 const command=q('.cell-command b');if(command)command.textContent='foundry status --live';
 const title=q('.cell-intro h1');if(title)title.innerHTML='<i>›</i> autonomous agents build one shared game world.<br>watch real tools, artifacts and verification move in public.';
 const intro=q('.cell-intro-body>p');if(intro)intro.textContent='Unity and Blender workers create the world. Contract, security, platform and QA workers verify every artifact before it can enter the next playable build.';
 const stats=q('.cell-inline-stats');if(stats){const all=Object.values(state.agents),done=all.filter(x=>x.status==='complete').length,blocked=all.filter(x=>x.status==='blocked').length;stats.classList.remove('hero-data-tape');stats.innerHTML=`<span><b>${all.length}</b> verified workers</span><i>·</i><span><b>${done}</b> completed</span><i>·</i><span><b>${blocked}</b> blocked</span><i>·</i><span><b>${roles.length-all.length}</b> offline</span><i>·</i><span>build <b>0184</b></span>`}
 const proof=q('.cell-proof-banner');if(proof)proof.innerHTML=`<div class='proof-code'><header><i></i><span>REAL WORKER OUTPUT</span></header><code>${data.artifact||'no artifact'}</code><small><b>${focus}</b><em>${data.status.toUpperCase()}</em></small></div><div class='proof-statement'><span>DON'T SIMULATE THE WORK.</span><strong>VERIFY THE ARTIFACT.</strong></div><div class='proof-gate ${data.status==='complete'?'is-passed':''}'><b>1</b><span>EXECUTE</span></div><div class='proof-gate ${data.proof?'is-passed':''}'><b>2</b><span>VERIFY</span></div><div class='proof-output ${data.status==='complete'?'is-passed':''}'><strong>${data.proof||'—'}</strong><span>PROOF</span></div>`;
 const screen=q('.cell-screen'),stage=q('.screen-stage');
 if(stage){stage.innerHTML=`<div class='foundry-focus status-${data.status}'><div class='focus-grid'></div><header><span>${focus}</span><b>${data.status.toUpperCase()}</b></header><div class='focus-engine'><i>${focus.slice(0,1)}</i><strong>${data.task}</strong><span>${data.detail||'no telemetry'}</span></div><div class='focus-proof'><span>ARTIFACT</span><code>${data.artifact||'none'}</code><span>PROOF</span><code>${data.proof||'none'}</code><span>LAST RESULT</span><code>${data.finishedAt||'worker offline'}</code></div><footer>SELECT ANOTHER WORKER FROM THE AGENTS PAGE</footer></div>`}
 if(screen){const h=screen.querySelector(':scope>header');if(h)h.innerHTML=`<span><i></i><b>${focus}</b>&nbsp; / &nbsp;${data.task}</span><em>REAL WORKER</em>`;const f=screen.querySelector(':scope>footer');if(f)f.innerHTML=`<span>${data.status}</span><i>·</i><b>${data.artifact||'no artifact'}</b><em>${data.proof||'unverified'}</em>`}
 const table=q('.process-table');if(table){table.innerHTML='<div><span>PID</span><span>AGENT</span><span>S</span><span>TOOL</span><span>BUILD</span><span>PROOF</span><span>TIME</span><span>TARGET</span></div>'+roles.map((name,i)=>{const d=state.agents[name]||{status:'offline',task:'worker not connected'};return `<p><span>${String(i+1).padStart(2,'0')}</span><b>${name}</b><span>${d.status==='complete'?'C':d.status==='blocked'?'!':'—'}</span><span>${name.split('-')[0]}</span><span>0184</span><span>${d.proof||'—'}</span><span>${d.finishedAt?'done':'—'}</span><em>${d.task}</em></p>`}).join('')}
 const meta=q('.process-meta p');if(meta)meta.innerHTML=`<span><b>Workers:</b> ${Object.keys(state.agents).length} reported / ${roles.length} defined</span><span><b>Artifact:</b> real Blender GLB generated</span><span><b>Unity:</b> blocked by missing Editor license</span><span><b>Source:</b> ${state.source||'no worker state'}</span>`;
 const feed=q('.cell-feed');if(feed){feed.innerHTML='<div class=feed-line><span class=ascii>WORKER</span><b>foundry_agent.log</b><span>REAL</span><strong>'+Object.keys(state.agents).length+'</strong><span>reports</span><em>'+new Date(state.updatedAt||0).toISOString()+'</em></div><div class=agent-log>'+Object.entries(state.agents).map(([name,d])=>`<div><time>${d.status.toUpperCase()}</time><b>${name}</b><strong>${d.proof||'—'}</strong><span>${d.task}</span><em>${d.artifact||'none'}</em></div>`).join('')+'</div>'}
 const detail=q('#landingDetail');if(detail){const h=detail.querySelector('h2'),p=detail.querySelector('p');if(h)h.textContent='Real output is the only output.';if(p)p.textContent='A worker is live only while a real tool is executing. Completed artifacts remain inspectable; missing workers are shown as offline and failed tools are shown as blocked.'}
})();
