(function(){window.VEEMO_PAGE_LIVE=true;document.body.classList.add('github-live-mounted');const h=document.head,l=document.createElement('link');l.rel='stylesheet';l.href='./page-stream-live.css?v=2';h.append(l);for(const file of ['assets/live-pages/manifest.js','page-stream-live.js']){const s=document.createElement('script');s.src='./'+file+'?v=2';s.async=false;h.append(s)}})();
(function(){
  if(window.VEEMO_PAGE_LIVE)return;
  const stage=document.querySelector('.screen-stage'),screen=document.querySelector('.cell-screen');
  if(!stage||!screen)return;
  document.body.classList.add('github-live-mounted');
  const state={channels:[],index:0,manualUntil:0,wallScanners:[],mainReadyAt:0,mainSwitching:false,sessionReads:0,lastTargetKey:'',scanPhase:'LOCKED'};
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const etTime=value=>new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(value?new Date(value):new Date());  const ago=value=>{const seconds=Math.max(0,Math.floor((Date.now()-Date.parse(value))/1000));if(seconds<60)return `${seconds}s ago`;if(seconds<3600)return `${Math.floor(seconds/60)}m ago`;if(seconds<86400)return `${Math.floor(seconds/3600)}h ago`;return `${Math.floor(seconds/86400)}d ago`};
  stage.innerHTML=`<div class="gh-native-live">
    <div class="gh-native-browser"><span class="browser-lights"><i></i><i></i><i></i></span><b>github.com</b><code data-gh="url">connecting…</code><a data-gh="external" href="https://github.com" target="_blank" rel="noopener">OPEN ↗</a></div>
    <nav class="gh-agent-channels" aria-label="Live GitHub agents"></nav>
    <section class="gh-native-page">
      <header class="gh-repository-head"><div><svg viewBox="0 0 16 16" aria-hidden="true"><path d="M2 2.75A1.75 1.75 0 0 1 3.75 1h8.5A1.75 1.75 0 0 1 14 2.75v10.5A1.75 1.75 0 0 1 12.25 15h-8.5A1.75 1.75 0 0 1 2 13.25ZM3.75 2.5a.25.25 0 0 0-.25.25v10.5c0 .138.112.25.25.25H5v-11Zm2.75 11h5.75a.25.25 0 0 0 .25-.25V2.75a.25.25 0 0 0-.25-.25H6.5Z"/></svg><strong data-gh="owner">github</strong><i>/</i><b data-gh="repo-name">repository</b><em>Public</em></div><aside><span>Watch <b data-gh="watchers">—</b></span><span>Fork <b data-gh="forks">—</b></span><span>Star <b data-gh="stars">—</b></span></aside></header>
      <nav class="gh-repository-nav"><b>⌘ Code</b><span>◉ Issues <i data-gh="issues">0</i></span><span>⑂ Pull requests</span><span>▶ Actions</span><span>▦ Projects</span><span>⌁ Security</span><span>▥ Insights</span></nav>
      <div class="gh-repository-body">
        <div class="gh-file-tools"><button>⑂ <b data-gh="branch">main</b>⌄</button><div class="gh-path"><span data-gh="repo-short">repo</span><i>/</i><b data-gh="path">source</b></div><button>Go to file</button><button class="code-button">&lt;&gt; Code⌄</button></div>
        <div class="gh-commit-bar"><span class="gh-avatar" data-gh="agent-initial">A</span><b data-gh="agent">agent</b><span data-gh="commit-title">latest public commit</span><code data-gh="sha">———————</code><time data-gh="push">now</time><strong>History</strong></div>
        <div class="gh-file-card"><header><span><i></i><b data-gh="file">source</b></span><aside><button>Raw</button><button>Blame</button><button>⌕</button><button>⋯</button></aside></header><div class="gh-native-code"><div class="gh-code-scroll"><ol aria-label="Live GitHub source"></ol></div><svg class="gh-code-map" aria-hidden="true"><g></g></svg><div class="gh-code-regions" aria-hidden="true"></div><span class="gh-native-agent"><i></i><b data-gh="cursor-agent">AGENT</b></span></div></div>
      </div>
    </section>
    <div class="gh-native-log"><header><b>LIVE AGENT OUTPUT</b><span data-gh="mode">REPOSITORY WATCH</span><em>READ-ONLY PUBLIC DATA</em></header><div data-gh="logs"></div></div>
  </div>`;
  const q=selector=>stage.querySelector(selector);
  function compact(value){const n=Number(value)||0;return n>=1000000?`${(n/1000000).toFixed(1)}m`:n>=1000?`${(n/1000).toFixed(1)}k`:String(n)}
  function heroMetrics(){const channels=state.channels,active=state.currentChannel||channels[0]||{},files=channels.flatMap(channel=>channel.files?.length?channel.files:[{path:channel.file,content:channel.content,lines:(channel.content||'').split('\n').length}]),stars=channels.reduce((sum,channel)=>sum+(Number(channel.stars)||0),0),forks=channels.reduce((sum,channel)=>sum+(Number(channel.forks)||0),0),issues=channels.reduce((sum,channel)=>sum+(Number(channel.issues)||0),0),lines=files.reduce((sum,file)=>sum+(Number(file.lines)||String(file.content||'').split('\n').length),0),row=q('.gh-code-scroll ol')?.children[state.mainTarget],kind=row?inspectKind(row.textContent,active.language)[0]:'WAITING';return {network:`${channels.length} AGENTS LIVE`,repositories:`${channels.length} PUBLIC REPOS`,sources:`${files.length} SOURCE FILES`,lines:`${lines.toLocaleString()} REAL LINES`,stars:`${compact(stars)} STARS`,forks:`${compact(forks)} FORKS`,issues:`${compact(issues)} OPEN ISSUES`,active:active.repo||'CONNECTING',file:active.file||'LOADING SOURCE',target:state.mainTarget!=null?`L${String(state.mainTarget+1).padStart(3,'0')} / ${kind}`:'ACQUIRING TARGET',revision:active.sha?.slice(0,9)||'SYNCING',reads:`${state.sessionReads} TARGETS READ`,phase:state.scanPhase,clock:`${etTime()} ET`}}
  function updateHeroTape(){const tape=document.querySelector('.hero-data-tape');if(!tape)return;const metrics=heroMetrics();for(const [key,value] of Object.entries(metrics))tape.querySelectorAll(`[data-hero="${key}"] em`).forEach(node=>node.textContent=value);const proof={file:metrics.file,target:metrics.target,revision:metrics.revision};for(const [key,value] of Object.entries(proof))document.querySelectorAll(`[data-proof="${key}"]`).forEach(node=>node.textContent=value);const steps=[...document.querySelectorAll('[data-proof-step]')],active=(state.mainStep||0)%Math.max(steps.length,1);steps.forEach((node,index)=>{node.classList.toggle('is-live',index===active);node.classList.toggle('is-passed',index<active)})}
  function mountHeroTape(){const tape=document.querySelector('.cell-inline-stats');if(!tape)return;tape.classList.add('hero-data-tape');const labels=[['network','NETWORK'],['repositories','REPOSITORIES'],['sources','SOURCE SET'],['lines','INDEXED'],['stars','REACH'],['forks','COPIES'],['issues','OPEN WORK'],['active','ACTIVE REPO'],['file','LIVE FILE'],['target','SCAN TARGET'],['revision','REVISION'],['reads','SESSION'],['phase','STATE'],['clock','NEW YORK']];const items=labels.map(([key,label])=>`<span data-hero="${key}"><b>${label}</b><em>SYNCING</em></span>`).join('');tape.innerHTML=`<div class="hero-live-track">${items}${items}</div>`;updateHeroTape()}
  function renderAgentProcesses(){const table=document.querySelector('.process-table');if(!table)return;table.querySelectorAll(':scope>p').forEach(row=>row.remove());state.channels.forEach((channel,index)=>{const row=document.createElement('p');row.dataset.agent=String(index);const files=channel.files?.length||1,values=[String(index+1).padStart(2,'0'),channel.agent,'R',channel.language,files,channel.issues||0,ago(channel.commitAt||channel.pushedAt),channel.repo];values.forEach((value,column)=>{const node=document.createElement(column===1?'b':column===7?'em':'span');node.textContent=value;row.append(node)});table.append(row)});const meta=document.querySelectorAll('.process-meta p span'),files=state.channels.reduce((sum,channel)=>sum+(channel.files?.length||1),0),issues=state.channels.reduce((sum,channel)=>sum+(Number(channel.issues)||0),0),values=[`<b>Fleet:</b> ${state.channels.length}/${state.channels.length} agents live`,`<b>Queue:</b> ${issues.toLocaleString()} public issues observed`,`<b>Dataset:</b> ${files} source files loaded`,`<b>Compute:</b> public GitHub repositories`];meta.forEach((node,index)=>{if(values[index])node.innerHTML=values[index]})}
  function pushVerificationEvent(channel,lineIndex,kind,codeText){const feed=document.querySelector('.cell-feed');if(!feed)return;const empty=feed.querySelector('.feed-empty');if(empty)empty.hidden=true;let log=feed.querySelector('.agent-log');if(!log){log=document.createElement('div');log.className='agent-log';feed.append(log)}const row=document.createElement('div'),time=document.createElement('time'),name=document.createElement('b'),verb=document.createElement('strong'),activity=document.createElement('span'),revision=document.createElement('em');time.textContent=`${etTime()} ET`;name.textContent=channel.agent;verb.textContent='SCAN';activity.textContent=`${channel.repo} · ${channel.file} · L${lineIndex+1} · ${kind[0]} · ${String(codeText||'').trim().slice(0,72)}`;revision.textContent=channel.sha?.slice(0,7)||'live';row.append(time,name,verb,activity,revision);log.prepend(row);while(log.children.length>9)log.lastElementChild.remove();const line=feed.querySelector('.feed-line');if(line){const spans=line.querySelectorAll('span');if(spans[0])spans[0].textContent=etTime();const title=line.querySelector('b');if(title)title.textContent='github_agent.log';if(spans[1])spans[1].textContent='LIVE';const count=line.querySelector('strong');if(count)count.textContent=String(state.sessionReads);if(spans[2])spans[2].textContent='targets inspected';const end=line.querySelector('em');if(end)end.textContent=`${channel.repo} · ${kind[1]}`}}
  function randomIndex(){if(state.channels.length<2)return 0;let next=state.index;while(next===state.index)next=Math.floor(Math.random()*state.channels.length);return next}
  function renderMain(index,manual=false,fileIndex=0){
    if(!state.channels.length)return;state.index=(index+state.channels.length)%state.channels.length;const baseChannel=state.channels[state.index],files=baseChannel.files?.length?baseChannel.files:[{path:baseChannel.file,content:baseChannel.content}],normalizedFile=((fileIndex%files.length)+files.length)%files.length,activeFile=files[normalizedFile];state.currentFileIndex=normalizedFile;state.currentChannel={...baseChannel,file:activeFile.path||baseChannel.file,content:activeFile.content||baseChannel.content,size:activeFile.size||baseChannel.size};state.overlaySegment=-1;if(manual)state.manualUntil=Date.now()+20000;
    const channel=state.currentChannel,parts=channel.repo.split('/'),path=`${channel.repo}/blob/${channel.branch||'main'}/${channel.file}`;
    stage.querySelectorAll('.gh-agent-channel').forEach((node,i)=>node.classList.toggle('active',i===state.index));document.querySelectorAll('.process-table>p[data-agent]').forEach((node,i)=>node.classList.toggle('is-active',i===state.index));
    q('[data-gh="url"]').textContent=path;q('[data-gh="external"]').href=`https://github.com/${path}`;
    q('[data-gh="owner"]').textContent=parts[0];q('[data-gh="repo-name"]').textContent=parts[1];q('[data-gh="repo-short"]').textContent=parts[1];q('[data-gh="path"]').textContent=channel.file;
    q('[data-gh="branch"]').textContent=channel.branch||'main';q('[data-gh="issues"]').textContent=compact(channel.issues);q('[data-gh="stars"]').textContent=compact(channel.stars);q('[data-gh="watchers"]').textContent=compact(channel.watchers??channel.stars);q('[data-gh="forks"]').textContent=compact(channel.forks);
    q('[data-gh="agent"]').textContent=channel.agent;q('[data-gh="agent-initial"]').textContent=channel.agent.slice(0,1).toUpperCase();q('[data-gh="cursor-agent"]').textContent=channel.agent;q('[data-gh="sha"]').textContent=channel.sha?.slice(0,7)||'offline';q('[data-gh="push"]').textContent=channel.commitAt?`${etTime(channel.commitAt)} ET`:channel.pushedAt?`${etTime(channel.pushedAt)} ET`:'unavailable';const commitTitle=q('[data-gh="commit-title"]');if(commitTitle)commitTitle.textContent=(channel.commitMessage||'latest public commit').slice(0,62);q('[data-gh="file"]').textContent=channel.file;q('[data-gh="mode"]').textContent=channel.mode;
    
    const lines=(channel.content||`// ${channel.error||'repository stream unavailable'}`).split('\n'),list=q('.gh-code-scroll ol');list.replaceChildren();lines.forEach((line,lineIndex)=>{const li=document.createElement('li'),code=document.createElement('code');li.value=lineIndex+1;code.textContent=line||' ';li.append(code);list.append(li)});
    const inspections=channel.language==='Python'?['CLASS INDEX','IMPORT GRAPH','ASYNC PATH']:channel.language==='C++'?['SYMBOL TABLE','HEADER GRAPH','MEMORY PATH']:channel.language==='Rust'?['TRAIT MAP','CRATE GRAPH','ACCOUNT PATH']:['PACKAGE MAP','CALL GRAPH','STATE PATH'],statuses=['INDEXING','TRACING','READING'],base=Math.min(Math.max(14,14+Math.floor(Math.random()*Math.max(5,lines.length-42))),Math.max(14,lines.length-22)),targets=[base,Math.min(lines.length-1,base+6),Math.min(lines.length-1,base+13)];
    targets.forEach((lineIndex,i)=>{const row=list.children[lineIndex];if(!row)return;row.classList.add('is-inspected',`inspect-row-${i+1}`);const marker=document.createElement('span');marker.className='gh-line-inspection';marker.innerHTML=`<i></i><b>${inspections[i]}</b><em>${statuses[i]}</em>`;row.append(marker)});
    const positionMain=()=>{const box=q('.gh-code-scroll'),agent=q('.gh-native-agent');if(!box.clientHeight)return;box.scrollTop=0;agent.style.top='16px';agent.style.left=Math.max(260,Math.min(box.clientWidth-74,540))+'px';state.mainReadyAt=performance.now()+2400;state.mainSwitching=false;state.mainStep=0;state.scanPhase='LOCKED';updateMainOverlay(true);updateHeroTape()};requestAnimationFrame(positionMain);setTimeout(positionMain,180);
    const stamp=`${etTime()} ET`,logs=q('[data-gh="logs"]');logs.innerHTML=`<p><time>${stamp}</time><b>${esc(channel.agent)}</b><span>GET github.com/${esc(channel.repo)}</span><strong>200</strong></p><p><time>${channel.commitAt?`${etTime(channel.commitAt)} ET`:stamp}</time><b>commit</b><span>${esc(channel.commitAuthor||'GitHub contributor')} · ${esc((channel.commitMessage||'latest public commit').slice(0,72))}</span><strong>${esc(channel.sha?.slice(0,7)||'—')}</strong></p><p><time>${stamp}</time><b>index</b><span>${esc(channel.file)} · ${lines.length} lines · ${esc(channel.language)}</span><strong>READ</strong></p>`;
    const heading=screen.querySelector(':scope>header');if(heading)heading.innerHTML=`<span><i></i><b>${esc(channel.agent)}</b>&nbsp; ${String(state.index+1).padStart(2,'0')}/${String(state.channels.length).padStart(2,'0')} &nbsp;›&nbsp; ${esc(channel.repo)}</span><em>LIVE GITHUB</em>`;
    const footer=screen.querySelector(':scope>footer');if(footer)footer.innerHTML=`<span>${esc(channel.mode)}</span><i>·</i><b>${esc(channel.repo)}@${esc(channel.branch||'main')}</b><em>${esc(channel.sha?.slice(0,7)||'offline')}</em>`;
  }
  function inspectKind(text,language){const value=String(text||'').trim();if(/^(import|from|use)\b|#include|require\(/.test(value))return ['DEPENDENCY','RESOLVING'];if(/\b(class|struct|trait|interface|enum)\b/.test(value))return ['SYMBOL','INDEXED'];if(/\b(def|fn|func|function)\b|\w+\s*\([^)]*\)\s*\{?$/.test(value))return ['ENTRY POINT','TRACING'];if(/\b(if|else|match|switch|case)\b/.test(value))return ['CONTROL FLOW','BRANCH'];if(/\b(await|async|yield|return)\b/.test(value))return ['DATA FLOW','FOLLOWING'];if(/\b(error|throw|except|catch|Result<|panic)\b/i.test(value))return ['FAILURE PATH','VERIFYING'];return [language==='Python'?'AST NODE':'CODE BLOCK','READING']}
  function semanticTarget(rows,start,end,seed,language){const candidates=[];for(let index=start;index<=end;index++){const code=rows[index]?.querySelector('code'),text=code?.textContent||'';if(!text.trim())continue;const kind=inspectKind(text,language);if(kind[0]!=='CODE BLOCK'&&kind[0]!=='AST NODE')candidates.push(index)}if(candidates.length)return candidates[seed%candidates.length];const fallback=[];for(let index=start;index<=end;index++)if((rows[index]?.querySelector('code')?.textContent||'').trim())fallback.push(index);return fallback.length?fallback[seed%fallback.length]:start}
  function drawTrail(svg,point,agentX,agentY,agentWidth){const group=svg.querySelector('g');group.replaceChildren();if(!point)return;const ns='http://www.w3.org/2000/svg',path=document.createElementNS(ns,'path'),attachX=agentX>=point.x?agentX:agentX+agentWidth,midX=point.x+(attachX-point.x)*.5;path.setAttribute('d',`M${point.x} ${point.y} H${midX} V${agentY} H${attachX}`);group.append(path);[point,{x:attachX,y:agentY}].forEach((node,index)=>{const dot=document.createElementNS(ns,'circle');dot.setAttribute('cx',String(node.x));dot.setAttribute('cy',String(node.y));dot.setAttribute('r',index?'2.5':'3');group.append(dot)})}
  function updateMainOverlay(force=false){const root=q('.gh-native-code'),box=q('.gh-code-scroll'),list=q('.gh-code-scroll ol'),regions=q('.gh-code-regions'),svg=q('.gh-code-map'),agent=q('.gh-native-agent'),channel=state.currentChannel;if(!root||!box||!list||!regions||!svg||!agent||!channel||!list.children.length)return;const rows=[...list.children],lineHeight=Math.max(10,rows[0].offsetHeight||11),first=Math.max(0,Math.floor(box.scrollTop/lineHeight)),visible=Math.max(8,Math.ceil(box.clientHeight/lineHeight)),segment=Math.floor(first/6),repoChanged=state.overlayRepo!==channel.repo,targetChanged=force||repoChanged||segment!==state.overlaySegment;state.overlayRepo=channel.repo;if(repoChanged||force){state.mainPoint=null}if(targetChanged){state.overlaySegment=segment;const start=Math.min(rows.length-1,first+1),end=Math.min(rows.length-1,first+visible-2),seed=[...`${channel.repo}:${segment}`].reduce((sum,char)=>sum+char.charCodeAt(0),0);state.mainTarget=semanticTarget(rows,start,end,seed,channel.language);state.mainSeed=seed;const targetKey=`${channel.repo}:${channel.file}:${state.mainTarget}`;if(targetKey!==state.lastTargetKey){state.lastTargetKey=targetKey;state.sessionReads++;const targetCode=rows[state.mainTarget]?.querySelector('code');pushVerificationEvent(channel,state.mainTarget,inspectKind(targetCode?.textContent,channel.language),targetCode?.textContent);updateHeroTape()}}const lineIndex=state.mainTarget??first,row=rows[lineIndex],code=row?.querySelector('code');if(!code)return;regions.replaceChildren();const rootRect=root.getBoundingClientRect(),codeRect=code.getBoundingClientRect(),rowRect=row.getBoundingClientRect(),left=Math.max(43,codeRect.left-rootRect.left-3),top=rowRect.top-rootRect.top-1;if(top<-2||top>rootRect.height-5)return;const regionWidth=Math.max(38,Math.min(codeRect.width+7,rootRect.width-left-8)),regionHeight=Math.max(11,rowRect.height+2),kind=inspectKind(code.textContent,channel.language),region=document.createElement('span');region.className='gh-code-region region-active';region.style.cssText=`top:${top}px;left:${left}px;width:${regionWidth}px;height:${regionHeight}px`;region.innerHTML=`<i>${String(lineIndex+1).padStart(3,'0')}</i><b>${kind[0]}</b><em>${kind[1]}</em>`;regions.append(region);const rightEdge=Math.min(rootRect.width-8,left+regionWidth),placeRight=rootRect.width-rightEdge>112,agentX=placeRight?rightEdge+46:Math.max(72,left-94),point={x:placeRight?rightEdge:left,y:top+regionHeight/2};state.mainPoint=point;const agentY=Math.max(25,Math.min(rootRect.height-38,point.y+28+((state.mainSeed||0)%19)));agent.style.left=`${agentX}px`;agent.style.top=`${agentY}px`;svg.setAttribute('viewBox',`0 0 ${rootRect.width} ${rootRect.height}`);drawTrail(svg,point,agentX,agentY+15,82)}
  function updateTileOverlay(scanner,force=false){const {tile,box,list,channel}=scanner,root=tile.querySelector('.repo-live-viewport'),svg=tile.querySelector('.repo-seq-trail'),region=tile.querySelector('.repo-seq-region'),agent=tile.querySelector('.repo-seq-agent');if(!root||!svg||!region||!agent||!list.children.length)return;const rows=[...list.children],lineHeight=Math.max(8,rows[0].offsetHeight||9),first=Math.max(0,Math.floor(box.scrollTop/lineHeight)),visible=Math.max(6,Math.ceil(box.clientHeight/lineHeight)),segment=Math.floor(first/5),targetChanged=force||segment!==scanner.overlaySegment;if(targetChanged){scanner.overlaySegment=segment;const start=Math.min(rows.length-1,first),end=Math.min(rows.length-1,first+visible-2);scanner.activeTarget=semanticTarget(rows,start,end,scanner.seed+segment,channel.language)}const target=scanner.activeTarget??first,row=rows[target],code=row?.querySelector('code');if(!code)return;const rootRect=root.getBoundingClientRect(),codeRect=code.getBoundingClientRect(),rowRect=row.getBoundingClientRect(),left=Math.max(30,codeRect.left-rootRect.left-2),top=rowRect.top-rootRect.top-1;if(top<84||top>rootRect.height-4)return;const width=Math.max(28,Math.min(codeRect.width+5,rootRect.width-left-5)),height=Math.max(9,rowRect.height+1),kind=inspectKind(code.textContent,channel.language);region.style.cssText=`top:${top}px;left:${left}px;width:${width}px;height:${height}px`;region.innerHTML=`<i>${String(scanner.windowStart+target+1).padStart(3,'0')}</i><b>${kind[0]}</b>`;const rightEdge=Math.min(rootRect.width-5,left+width),placeRight=rootRect.width-rightEdge>78,agentX=placeRight?rightEdge+28:Math.max(40,left-58),point={x:placeRight?rightEdge:left,y:top+height/2};scanner.activePoint=point;const agentY=Math.max(94,Math.min(rootRect.height-26,point.y+18+(scanner.seed%13)));agent.style.left=`${agentX}px`;agent.style.top=`${agentY}px`;svg.setAttribute('viewBox',`0 0 ${rootRect.width} ${rootRect.height}`);drawTrail(svg,point,agentX,agentY+10,54)}
  function wallLabels(channel){return channel.language==='Python'?['CLASS','IMPORT']:channel.language==='C++'?['SYMBOL','HEADER']:channel.language==='Rust'?['TRAIT','ACCOUNT']:['PACKAGE','CALL']}
  function fillWallScanner(scanner,start){
    const {list,lines,channel,index,box}=scanner,windowSize=Math.min(54,lines.length),pageCount=Math.max(1,Math.ceil(lines.length/windowSize)),page=((Math.floor(start/windowSize)%pageCount)+pageCount)%pageCount;scanner.page=page;scanner.windowSize=windowSize;scanner.windowStart=Math.min(page*windowSize,Math.max(0,lines.length-windowSize));const windowLines=lines.slice(scanner.windowStart,scanner.windowStart+windowSize),labels=wallLabels(channel);list.replaceChildren();windowLines.forEach((line,lineIndex)=>{const row=document.createElement('li'),code=document.createElement('code');row.value=scanner.windowStart+lineIndex+1;code.textContent=line||' ';row.append(code);list.append(row)});const first=Math.min(windowLines.length-1,7+(scanner.seed%11)),targets=[first,Math.min(windowLines.length-1,first+9+(index%6))];targets.forEach((lineIndex,targetIndex)=>{const row=list.children[lineIndex];if(!row)return;row.classList.add('is-agent-target');const marker=document.createElement('span');marker.className='repo-line-marker';marker.innerHTML=`<i></i><b>${labels[targetIndex]}</b><em>${targetIndex?'TRACE':'INDEX'}</em>`;row.append(marker);if(targetIndex===0){const cursor=document.createElement('span');cursor.className='repo-line-agent';cursor.innerHTML=`<i></i><b>${esc(channel.agent)}</b>`;row.append(cursor)}});const rangeLabel=scanner.tile.querySelector('[data-scan-range]');if(rangeLabel)rangeLabel.textContent=`L${scanner.windowStart+1}–${scanner.windowStart+windowLines.length}`;box.scrollTop=0;scanner.readyAt=performance.now()+1800+(scanner.seed%900);scanner.cycle=(scanner.cycle||0)+1;scanner.overlaySegment=-1;scanner.trail=[];scanner.activePoint=null;scanner.activeTarget=null;requestAnimationFrame(()=>updateTileOverlay(scanner,true))
  }
  function renderWall(){
    const wall=document.querySelector('.machine-wall'),command=document.querySelector('.machine-command');if(!wall)return;wall.replaceChildren();wall.classList.remove('eight');wall.classList.add('repo-live-wall','twelve','github-synced-wall');state.wallScanners=[];
    state.channels.forEach((channel,index)=>{
      const tile=document.createElement('article'),lines=(channel.content||channel.error||'stream unavailable').split('\n'),seed=[...channel.repo].reduce((sum,char)=>sum+char.charCodeAt(0),0),parts=channel.repo.split('/');tile.className='repo-live-tile';tile.tabIndex=0;
      tile.innerHTML=`<header><span><i></i>${String(index+1).padStart(2,'0')} / ${esc(channel.agent)}</span><b>LIVE</b></header><div class="repo-live-viewport repo-sync-viewport"><div class="repo-mini-browser">github.com/${esc(channel.repo)}</div><div class="repo-sync-repository"><strong>${esc(parts[0])} <i>/</i> ${esc(parts[1])}</strong><em>Public</em><span>★ ${compact(channel.stars)}</span></div><div class="repo-sync-nav"><b>⌘ Code</b><span>Issues ${compact(channel.issues)}</span><span>Pull requests</span><span>Actions</span></div><div class="repo-sync-file"><span>${esc(channel.branch||'main')}</span><b data-repo-file>${esc(channel.file)}</b><code>${esc(channel.sha?.slice(0,7)||'offline')}</code></div><div class="repo-live-scroll"><ol class="repo-tile-code"></ol></div><svg class="repo-seq-trail" aria-hidden="true"><g></g></svg><span class="repo-seq-region" aria-hidden="true"></span><span class="repo-seq-agent" aria-hidden="true"><i></i><b>${esc(channel.agent)}</b></span></div><footer><span>${esc(channel.mode)}</span><b data-scan-range>loading</b><em>open ↗</em></footer>`;
      const files=channel.files?.length?channel.files:[{path:channel.file,content:channel.content}],scanner={tile,list:tile.querySelector('.repo-tile-code'),box:tile.querySelector('.repo-live-scroll'),lines,channel,baseChannel:channel,files,fileIndex:0,index,seed,speed:.72+(seed%10)*.12,windowStart:0,cycle:0,readyAt:0};const open=()=>{location.hash='live';renderMain(index,true,scanner.fileIndex)};tile.addEventListener('click',open);tile.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();open()}});wall.append(tile);fillWallScanner(scanner,(seed*(index+3))%Math.max(1,lines.length));state.wallScanners.push(scanner)
    });
    const title=command?.querySelector('b'),summary=command?.querySelector('em'),buttons=command?.querySelectorAll('nav button');if(title)title.textContent='github live --top-to-bottom --refresh';if(summary)summary.textContent=`# ${state.channels.length} synchronized GitHub streams`;if(buttons?.[0])buttons[0].textContent='[r]epos';if(buttons?.[1])buttons[1].textContent='[t]asks';if(buttons?.[2])buttons[2].textContent=`[a]gents ${state.channels.length}`;if(buttons?.[3])buttons[3].textContent='[c]rypto 5';if(buttons?.[4])buttons[4].textContent='[a]i 7';if(buttons?.[5])buttons[5].textContent=`[l]ive ${state.channels.length}`;if(buttons?.[6])buttons[6].textContent='[e]rrors 0';const status=document.querySelector('.machine-wall-status>span');if(status)status.innerHTML='<b>veemo</b> "github live · downward scan · refresh at end"'
  }
  function animateWall(time){for(const scanner of state.wallScanners){if(time<scanner.readyAt)continue;const max=scanner.box.scrollHeight-scanner.box.clientHeight;if(max<=0)continue;if(scanner.box.scrollTop>=max-1){scanner.seed=(scanner.seed*1664525+1013904223)>>>0;const pageCount=Math.max(1,Math.ceil(scanner.lines.length/(scanner.windowSize||54))),nextPage=((scanner.page||0)+1)%pageCount;if(nextPage===0&&scanner.files.length>1){scanner.fileIndex=(scanner.fileIndex+1)%scanner.files.length;const activeFile=scanner.files[scanner.fileIndex];scanner.lines=(activeFile.content||'stream unavailable').split('\n');scanner.channel={...scanner.baseChannel,file:activeFile.path,content:activeFile.content};const fileNode=scanner.tile.querySelector('[data-repo-file]');if(fileNode)fileNode.textContent=activeFile.path;fillWallScanner(scanner,0)}else fillWallScanner(scanner,nextPage*(scanner.windowSize||54));continue}const root=scanner.tile.querySelector('.repo-live-viewport'),lineHeight=Math.max(8,scanner.list.children[0]?.offsetHeight||9),stepLines=5+(scanner.seed+scanner.cycle)%5;root?.classList.add('is-relocating');scanner.box.scrollTo({top:Math.min(max,scanner.box.scrollTop+lineHeight*stepLines),behavior:'smooth'});scanner.readyAt=time+2200+(scanner.seed%700);setTimeout(()=>{root?.classList.remove('is-relocating');scanner.overlaySegment=-1;updateTileOverlay(scanner,true)},460)}}  function renderBrief(){let brief=document.querySelector('.cell-network-brief');if(!brief){brief=document.createElement('div');brief.className='cell-network-brief';document.querySelector('.cell-process')?.prepend(brief)}brief.innerHTML=`<header><b>LIVE TARGET MATRIX</b><span>${state.channels.length} autonomous agents · official public repositories</span><em>TOP → BOTTOM</em></header><div>${state.channels.map((channel,index)=>`<span><i>${String(index+1).padStart(2,'0')}</i><b>${esc(channel.repo.split('/')[1])}</b><em>${esc(channel.language)}</em></span>`).join('')}</div>`;let note=document.querySelector('.cell-network-note');if(!note){note=document.createElement('div');note.className='cell-network-note';brief?.after(note)}note.innerHTML='<b>OPERATING RULE</b><span>discover issue → reproduce → patch → test → independent replay ×2 → pull request</span><em>ALL READS PUBLIC</em>';renderAgentProcesses();mountHeroTape()}
  function mount(){const nav=q('.gh-agent-channels');nav.replaceChildren();state.channels.forEach((channel,index)=>{const button=document.createElement('button');button.className='gh-agent-channel';button.innerHTML=`<span>${String(index+1).padStart(2,'0')}</span><b>${esc(channel.repo.split('/')[1])}</b><i>${esc(channel.agent)}</i>`;button.addEventListener('click',()=>renderMain(index,true));nav.append(button)});renderWall();renderBrief();renderMain(Math.floor(Math.random()*state.channels.length))}
  async function load(){let lastError;for(const url of ['/api/github-stream','./assets/github-stream.json']){try{const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`${url} · HTTP ${response.status}`);state.channels=(await response.json()).channels||[];if(!state.channels.length)throw new Error('no repository channels');mount();return}catch(error){lastError=error}}q('.gh-native-code ol').innerHTML=`<li><code>stream error: ${esc(lastError?.message||'data unavailable')}</code></li>`}
  setInterval(()=>{const box=q('.gh-code-scroll'),root=q('.gh-native-code'),now=performance.now();if(!box||now<state.mainReadyAt||state.mainSwitching)return;const max=box.scrollHeight-box.clientHeight;if(max<=0)return;if(box.scrollTop>=max-1){state.mainSwitching=true;const files=state.channels[state.index].files?.length?state.channels[state.index].files:[{path:state.channels[state.index].file,content:state.channels[state.index].content}],nextFile=state.currentFileIndex+1;if(nextFile<files.length)renderMain(state.index,false,nextFile);else renderMain((state.index+1)%state.channels.length,false,0);return}const lineHeight=Math.max(10,box.querySelector('li')?.offsetHeight||11),stepLines=7+((state.mainSeed||0)+state.mainStep)%6;state.mainStep=(state.mainStep||0)+1;state.scanPhase='MOVING';updateHeroTape();root?.classList.add('is-relocating');box.scrollTo({top:Math.min(max,box.scrollTop+lineHeight*stepLines),behavior:'smooth'});state.mainReadyAt=now+3000;setTimeout(()=>{root?.classList.remove('is-relocating');state.scanPhase='LOCKED';state.overlaySegment=-1;updateMainOverlay(true);updateHeroTape()},560)},100);  setInterval(()=>animateWall(performance.now()),40);setInterval(updateHeroTape,1000);load();setInterval(load,90000);
})();
