import http from 'node:http';
import { createReadStream, existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { extname, isAbsolute, normalize, relative, resolve } from 'node:path';
import { createHash, randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';

const root=resolve(import.meta.dirname),dataDir=resolve(process.env.VEEMO_DATA_DIR||resolve(root,'data')),dataFile=resolve(dataDir,'state.json');
const port=Number(process.env.PORT||4210),host=process.env.HOST||'127.0.0.1',adminToken=process.env.VEEMO_ADMIN_TOKEN||'',registrationKey=process.env.VEEMO_REGISTRATION_KEY||'';
const clients=new Set(),rate=new Map(),metrics={startedAt:Date.now(),requests:0};
const githubChannels=[
  {repo:'bitcoin/bitcoin',branch:'master',language:'C++',stars:90305,forks:39426,file:'src/net.cpp',agent:'helix-01',mode:'BITCOIN P2P'},
  {repo:'ethereum/go-ethereum',branch:'master',language:'Go',stars:51383,forks:22159,file:'cmd/geth/main.go',agent:'vector-02',mode:'EVM CLIENT'},
  {repo:'huggingface/transformers',branch:'main',language:'Python',stars:166927,forks:34742,file:'src/transformers/models/llama/modeling_llama.py',agent:'kiln-03',mode:'TRANSFORMER RUNTIME'},
  {repo:'openai/openai-python',branch:'main',language:'Python',stars:31741,forks:6981,file:'src/openai/_client.py',agent:'cobalt-04',mode:'AI SDK'},
  {repo:'anza-xyz/agave',branch:'master',language:'Rust',stars:1930,forks:1227,file:'programs/system/src/system_processor.rs',agent:'orbit-05',mode:'SOLANA RUNTIME'},
  {repo:'pytorch/pytorch',branch:'main',language:'Python',stars:103697,forks:31257,file:'torch/nn/modules/module.py',agent:'tensor-06',mode:'TENSOR ENGINE'},
  {repo:'tensorflow/tensorflow',branch:'master',language:'C++',stars:200680,forks:78201,file:'tensorflow/core/framework/tensor.cc',agent:'matrix-07',mode:'ML KERNEL'},
  {repo:'langchain-ai/langchain',branch:'master',language:'Python',stars:147415,forks:24695,file:'libs/core/langchain_core/runnables/base.py',agent:'beacon-08',mode:'AGENT FRAMEWORK'},
  {repo:'paradigmxyz/reth',branch:'main',language:'Rust',stars:5807,forks:2558,file:'crates/node/core/src/node_config.rs',agent:'forge-09',mode:'EVM EXECUTION'},
  {repo:'MystenLabs/sui',branch:'main',language:'Rust',stars:7763,forks:11648,file:'crates/sui-node/src/lib.rs',agent:'nexus-10',mode:'OBJECT CHAIN'},
  {repo:'vllm-project/vllm',branch:'main',language:'Python',stars:68000,forks:13000,file:'vllm/v1/engine/core.py',agent:'prism-11',mode:'LLM INFERENCE'},
  {repo:'ollama/ollama',branch:'main',language:'Go',stars:154000,forks:14000,file:'server/routes.go',agent:'ember-12',mode:'LOCAL MODEL RUNTIME'}
];
const githubCacheFile=resolve(dataDir,'github-cache.json');
let githubCache=existsSync(githubCacheFile)?{...JSON.parse(readFileSync(githubCacheFile,'utf8')),refreshing:null}:{at:0,channels:[],refreshing:null};
const emptyState=()=>({version:2,createdAt:new Date().toISOString(),tasks:[],machines:[],mutations:[],lineage:[],events:[],treasury:{network:'solana',initialized:false,address:null,balanceSol:null}});
mkdirSync(dataDir,{recursive:true});let state=existsSync(dataFile)?JSON.parse(readFileSync(dataFile,'utf8')):emptyState();state.tasks||=[];state.version=2;
function persist(){const tmp=`${dataFile}.tmp`;writeFileSync(tmp,JSON.stringify(state,null,2));renameSync(tmp,dataFile)}
function hash(value){return createHash('sha256').update(value).digest('hex')}
function equal(a,b){const x=Buffer.from(a||''),y=Buffer.from(b||'');return x.length===y.length&&timingSafeEqual(x,y)}
function now(){return new Date().toISOString()}
function id(prefix){return `${prefix}_${randomUUID().replaceAll('-','').slice(0,12)}`}
function cleanMachine(machine){const {secretHash,...item}=machine;return {...item,status:Date.now()-Date.parse(machine.lastSeenAt)<45000?machine.status:'offline'}}
function cleanMutation(mutation){const {patch,...item}=mutation;return {...item,patchBytes:patch?Buffer.byteLength(patch):0}}
function publicState(){return {version:state.version,createdAt:state.createdAt,tasks:state.tasks,machines:state.machines.map(cleanMachine),mutations:state.mutations.map(cleanMutation),lineage:state.lineage,events:state.events.slice(0,100),treasury:state.treasury}}
function persistEvent(type,payload={}){const event={id:id('evt'),type,at:now(),payload};state.events.unshift(event);state.events=state.events.slice(0,250);persist();const message=`id: ${event.id}\nevent: ${type}\ndata: ${JSON.stringify(event)}\n\n`;for(const response of clients)response.write(message);return event}
function json(response,status,value){response.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});response.end(JSON.stringify(value))}
async function body(request){const parts=[];let bytes=0;for await(const chunk of request){bytes+=chunk.length;if(bytes>600000)throw new Error('request body exceeds 600KB');parts.push(chunk)}return parts.length?JSON.parse(Buffer.concat(parts).toString('utf8')):{}}
function machineAuth(request){const token=request.headers.authorization?.replace(/^Bearer\s+/i,'');return token?state.machines.find(machine=>equal(machine.secretHash,hash(token)))||null:null}
function isLoopback(request){return ['127.0.0.1','::1','::ffff:127.0.0.1'].includes(request.socket.remoteAddress)}
function adminAuth(request){if(!adminToken)return isLoopback(request);return equal(request.headers.authorization?.replace(/^Bearer\s+/i,''),adminToken)}
function limit(request){const key=request.socket.remoteAddress||'unknown',minute=Math.floor(Date.now()/60000),entry=rate.get(key);if(!entry||entry.minute!==minute){rate.set(key,{minute,count:1});return true}entry.count++;return entry.count<=600}
function validName(value){return typeof value==='string'&&/^[a-z0-9][a-z0-9-]{2,23}$/.test(value)}
function finite(value){return Number.isFinite(Number(value))}
function command(value){return Array.isArray(value)&&value.length>0&&value.length<=24&&value.every(part=>typeof part==='string'&&part.length>0&&part.length<=240)}
function staticFile(response,pathname){const requested=pathname==='/'?'index.html':pathname.slice(1),publicFiles=new Set(['index.html','styles.css','app.js','runtime.js','github-live.js','product-pages.js']);if(!publicFiles.has(requested)&&!requested.startsWith('assets/'))return false;const file=resolve(root,normalize(requested)),rel=relative(root,file);if(rel.startsWith('..')||isAbsolute(rel)||!existsSync(file))return false;const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.png':'image/png','.svg':'image/svg+xml','.webp':'image/webp'};response.writeHead(200,{'content-type':types[extname(file)]||'application/octet-stream','cache-control':'no-cache','x-content-type-options':'nosniff'});createReadStream(file).pipe(response);return true}

async function githubRequest(url){const result=await fetch(url,{headers:{accept:'application/vnd.github+json','user-agent':'veemo-live/1.0','x-github-api-version':'2022-11-28'}});if(!result.ok)throw new Error(`GitHub ${result.status}`);return result.json()}
async function githubRawText(channel,branch,index,file=channel.file){let lastError;for(let attempt=0;attempt<4;attempt++){try{if(attempt===0&&index)await new Promise(resolve=>setTimeout(resolve,index*140));const result=await fetch(`https://raw.githubusercontent.com/${channel.repo}/${branch}/${file}`,{headers:{'user-agent':'veemo-live/1.0'}});if(!result.ok)throw new Error(`GitHub raw ${result.status}`);return await result.text()}catch(error){lastError=error;if(attempt<3)await new Promise(resolve=>setTimeout(resolve,300*(attempt+1)+index*45))}}throw lastError}
function sourceExtensions(language){if(language==='Python')return ['.py'];if(language==='Rust')return ['.rs'];if(language==='Go')return ['.go'];if(language==='C++')return ['.cpp','.cc','.cxx','.h','.hpp'];return ['.js','.ts','.tsx']}
function sourceRank(item,rootDir){const depth=item.path.split('/').length,sameRoot=item.path.startsWith(`${rootDir}/`)?-80:0,sourceDir=/(^|\/)(src|lib|core|runtime|programs|torch|tensorflow)(\/|$)/.test(item.path)?-35:0;return sameRoot+sourceDir+depth*5+Math.abs((item.size||12000)-18000)/5000}
async function githubSourceFiles(channel,branch,index){let tree=[];try{const result=await githubRequest(`https://api.github.com/repos/${channel.repo}/git/trees/${encodeURIComponent(branch)}?recursive=1`);tree=Array.isArray(result.tree)?result.tree:[]}catch{}const extensions=sourceExtensions(channel.language),rootDir=channel.file.split('/')[0],candidates=tree.filter(item=>item.type==='blob'&&(item.size||0)>1200&&(item.size||0)<220000&&extensions.some(ext=>item.path.endsWith(ext))&&!/(^|\/)(test|tests|testing|docs|examples|vendor|third_party|generated|build|dist|fixtures)(\/|$)/i.test(item.path)&&item.path!==channel.file).sort((a,b)=>sourceRank(a,rootDir)-sourceRank(b,rootDir));const paths=[channel.file,...candidates.slice(0,5).map(item=>item.path)].filter((file,position,all)=>all.indexOf(file)===position).slice(0,5),files=[];for(let fileIndex=0;fileIndex<paths.length;fileIndex++){const file=paths[fileIndex];try{const source=(await githubRawText(channel,branch,index,file)).replaceAll('\r',''),content=source.split('\n').slice(0,240).join('\n');if(content.trim())files.push({path:file,content,size:Buffer.byteLength(source),lines:source.split('\n').length})}catch{}}if(!files.length)throw new Error('no readable source files');return files}
async function githubStream(){
  if(Date.now()-githubCache.at<1800000&&githubCache.channels.length===githubChannels.length&&githubCache.channels.every(item=>item.content&&item.commitAt&&item.commitUrl&&Array.isArray(item.files)&&item.files.length>1))return githubCache;
  if(githubCache.refreshing)return githubCache.refreshing;
  githubCache.refreshing=Promise.all(githubChannels.map(async(channel,index)=>{
    try{
      let repository={};try{repository=await githubRequest(`https://api.github.com/repos/${channel.repo}`)}catch{}
      const branch=repository.default_branch||channel.branch,files=await githubSourceFiles(channel,branch,index),source=files[0].content,content=source;
      let commit={};try{commit=await githubRequest(`https://api.github.com/repos/${channel.repo}/commits/${encodeURIComponent(branch)}`)}catch{}
      const commitSha=commit.sha||hash(source),commitAt=commit.commit?.author?.date||repository.pushed_at||null;
      return {...channel,url:repository.html_url||`https://github.com/${channel.repo}`,branch,language:repository.language||channel.language,description:repository.description||'official public repository',stars:repository.stargazers_count??channel.stars,forks:repository.forks_count??channel.forks,watchers:repository.subscribers_count??channel.stars,issues:repository.open_issues_count??0,pushedAt:repository.pushed_at||commitAt,sha:commitSha,contentSha:hash(source),commitUrl:commit.html_url||`https://github.com/${channel.repo}/commit/${commitSha}`,commitMessage:commit.commit?.message?.split('\n')[0]||'latest public revision',commitAuthor:commit.commit?.author?.name||commit.author?.login||'GitHub contributor',commitAt,size:files[0].size,content,files,file:files[0].path,source:'raw.githubusercontent.com'};
    }catch(error){const stale=githubCache.channels.find(item=>item.repo===channel.repo&&item.content);return stale?{...stale,stale:true,warning:error.message}:{...channel,url:`https://github.com/${channel.repo}`,watchers:channel.stars,issues:0,error:error.message,content:''}}
  })).then(channels=>{const next={at:Date.now(),channels};writeFileSync(githubCacheFile,JSON.stringify(next));return githubCache={...next,refreshing:null}}).catch(error=>{githubCache.refreshing=null;throw error});
  return githubCache.refreshing;
}const server=http.createServer(async(request,response)=>{metrics.requests++;const url=new URL(request.url,`http://${request.headers.host||'localhost'}`),path=url.pathname;response.setHeader('x-frame-options','DENY');response.setHeader('referrer-policy','no-referrer');response.setHeader('content-security-policy',"default-src 'self'; img-src 'self' data:; style-src 'self' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; script-src 'self'; connect-src 'self'");try{
if(!limit(request))return json(response,429,{error:'rate limit exceeded'});
if(request.method==='GET'&&path==='/api/health')return json(response,200,{ok:true,service:'veemo-core',version:state.version,time:now(),uptimeSec:Math.floor(process.uptime())});
if(request.method==='GET'&&path==='/api/github-stream')return json(response,200,await githubStream());
if(request.method==='GET'&&path==='/api/telemetry'){const memory=process.memoryUsage(),online=state.machines.map(cleanMachine).filter(machine=>machine.status!=='offline').length;return json(response,200,{at:now(),startedAt:new Date(metrics.startedAt).toISOString(),uptimeSec:Math.floor(process.uptime()),pid:process.pid,rssMb:Number((memory.rss/1048576).toFixed(1)),heapMb:Number((memory.heapUsed/1048576).toFixed(1)),requests:metrics.requests,sseClients:clients.size,onlineMachines:online,totalMachines:state.machines.length,openTasks:state.tasks.filter(task=>task.status==='open').length,verifying:state.mutations.filter(item=>item.status==='verifying').length,generations:state.lineage.length,events:state.events.length})}
if(request.method==='GET'&&path==='/api/state')return json(response,200,publicState());
if(request.method==='GET'&&path==='/api/events'){response.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache',connection:'keep-alive'});response.write(`event: snapshot\ndata: ${JSON.stringify(publicState())}\n\n`);clients.add(response);request.on('close',()=>clients.delete(response));return}
if(request.method==='GET'&&path==='/api/tasks')return json(response,200,{tasks:state.tasks});
const mutationRead=path.match(/^\/api\/mutations\/([^/]+)$/);if(request.method==='GET'&&mutationRead){const mutation=state.mutations.find(item=>item.id===mutationRead[1]);return mutation?json(response,200,{mutation}):json(response,404,{error:'mutation not found'})}
if(request.method==='POST'&&path==='/api/tasks'){if(!adminAuth(request))return json(response,401,{error:'admin bearer token required'});const input=await body(request);if(!/^https:\/\/.+/i.test(input.repository||'')||!/^[a-f0-9]{7,64}$/i.test(input.baseCommit||''))return json(response,422,{error:'valid HTTPS repository and baseCommit are required'});if(!command(input.testCommand)||!command(input.benchmarkCommand))return json(response,422,{error:'testCommand and benchmarkCommand must be argument arrays'});if(!/^[a-z0-9][a-z0-9._/:@-]{0,127}$/i.test(input.dockerImage||''))return json(response,422,{error:'valid dockerImage is required'});const task={id:id('task'),title:String(input.title||'Untitled optimization').slice(0,120),repository:String(input.repository).slice(0,300),baseCommit:String(input.baseCommit),target:String(input.target||'repository').slice(0,180),dockerImage:String(input.dockerImage),testCommand:input.testCommand,benchmarkCommand:input.benchmarkCommand,metric:String(input.metric||'metric').slice(0,80),lowerIsBetter:input.lowerIsBetter!==false,minGainPct:Math.max(0,Number(input.minGainPct)||0),status:'open',createdAt:now(),claimedBy:null};state.tasks.unshift(task);persistEvent('task.created',{task});return json(response,201,{task})}
const claim=path.match(/^\/api\/tasks\/([^/]+)\/claim$/);if(request.method==='POST'&&claim){const machine=machineAuth(request);if(!machine)return json(response,401,{error:'valid machine bearer token required'});const task=state.tasks.find(item=>item.id===claim[1]);if(!task)return json(response,404,{error:'task not found'});if(task.status!=='open'&&task.claimedBy!==machine.id)return json(response,409,{error:'task already claimed'});task.status='claimed';task.claimedBy=machine.id;task.claimedAt=now();persistEvent('task.claimed',{task,machine:cleanMachine(machine)});return json(response,200,{task})}
if(request.method==='POST'&&path==='/api/machines/register'){const input=await body(request);if(registrationKey&&!equal(String(input.registrationKey||request.headers['x-veemo-registration-key']||''),registrationKey))return json(response,403,{error:'valid registration key required'});if(!validName(input.name))return json(response,422,{error:'name must be 3-24 lowercase letters, numbers or hyphens'});if(state.machines.some(machine=>machine.name===input.name))return json(response,409,{error:'machine name already registered'});const secret=`cell_sk_${randomBytes(24).toString('base64url')}`,machine={id:id('machine'),name:input.name,target:String(input.target||'general').slice(0,80),repository:String(input.repository||'').slice(0,240),wallet:input.wallet?String(input.wallet).slice(0,64):null,resources:{cpu:Math.max(1,Math.min(128,Number(input.cpu)||1)),memoryGb:Math.max(1,Math.min(512,Number(input.memoryGb)||1))},status:'online',createdAt:now(),lastSeenAt:now(),secretHash:hash(secret)};state.machines.push(machine);persistEvent('machine.registered',{machine:cleanMachine(machine)});return json(response,201,{machine:cleanMachine(machine),secret,warning:'Store this secret now. It is never returned again.'})}
if(request.method==='POST'&&path==='/api/machines/heartbeat'){const machine=machineAuth(request);if(!machine)return json(response,401,{error:'valid machine bearer token required'});const input=await body(request);machine.lastSeenAt=now();machine.status=input.status==='busy'?'busy':'online';machine.activity=String(input.activity||machine.activity||'polling verification queue').slice(0,120);if(finite(input.load))machine.load=Math.max(0,Math.min(1,Number(input.load)));persist();return json(response,200,{ok:true,machine:cleanMachine(machine)})}
if(request.method==='POST'&&path==='/api/mutations'){const machine=machineAuth(request);if(!machine)return json(response,401,{error:'valid machine bearer token required'});const input=await body(request),task=state.tasks.find(item=>item.id===input.taskId);if(!task)return json(response,422,{error:'valid taskId required'});if(task.claimedBy!==machine.id)return json(response,409,{error:'machine must claim this task first'});if(typeof input.patch!=='string'||!input.patch.trim()||Buffer.byteLength(input.patch)>400000)return json(response,422,{error:'non-empty unified patch under 400KB required'});const patchDigest=hash(input.patch);if(input.patchDigest&&input.patchDigest!==patchDigest)return json(response,422,{error:'patchDigest does not match patch content'});if(!finite(input.baselineMetric)||!finite(input.candidateMetric)||Number(input.baselineMetric)<=0)return json(response,422,{error:'positive baselineMetric and candidateMetric required'});const baseline=Number(input.baselineMetric),candidate=Number(input.candidateMetric),gain=task.lowerIsBetter?((baseline-candidate)/baseline)*100:((candidate-baseline)/baseline)*100;if(gain<=task.minGainPct)return json(response,422,{error:`gain must exceed ${task.minGainPct}%`});const mutation={id:id('mutation'),taskId:task.id,machineId:machine.id,machineName:machine.name,repository:task.repository,target:task.target,baseCommit:task.baseCommit,patchDigest,patch:input.patch,summary:String(input.summary||'').slice(0,500),metric:task.metric,baselineMetric:baseline,candidateMetric:candidate,lowerIsBetter:task.lowerIsBetter,claimedGainPct:Number(gain.toFixed(4)),testsPassed:input.testsPassed===true,status:input.testsPassed===true?'verifying':'rejected',createdAt:now(),verifications:[]};state.mutations.unshift(mutation);task.status=mutation.status==='verifying'?'verifying':'open';persistEvent(`mutation.${mutation.status}`,{mutation:cleanMutation(mutation)});return json(response,201,{mutation:cleanMutation(mutation)})}
const verify=path.match(/^\/api\/mutations\/([^/]+)\/verify$/);if(request.method==='POST'&&verify){const machine=machineAuth(request);if(!machine)return json(response,401,{error:'valid machine bearer token required'});const mutation=state.mutations.find(item=>item.id===verify[1]);if(!mutation)return json(response,404,{error:'mutation not found'});if(mutation.machineId===machine.id)return json(response,409,{error:'author machine cannot verify its own mutation'});if(mutation.status!=='verifying')return json(response,409,{error:`mutation is ${mutation.status}`});if(mutation.verifications.some(item=>item.machineId===machine.id))return json(response,409,{error:'machine already verified this mutation'});const input=await body(request);if(!finite(input.observedMetric)||!finite(input.observedBaselineMetric))return json(response,422,{error:'observedBaselineMetric and observedMetric are required'});const observed=Number(input.observedMetric),observedBaseline=Number(input.observedBaselineMetric),candidateDrift=Math.abs(observed-mutation.candidateMetric)/Math.max(Math.abs(mutation.candidateMetric),1e-9),baselineDrift=Math.abs(observedBaseline-mutation.baselineMetric)/Math.max(Math.abs(mutation.baselineMetric),1e-9),passed=input.testsPassed===true&&candidateDrift<=.05&&baselineDrift<=.05;mutation.verifications.push({machineId:machine.id,machineName:machine.name,testsPassed:input.testsPassed===true,observedBaselineMetric:observedBaseline,observedMetric:observed,candidateDrift:Number(candidateDrift.toFixed(6)),baselineDrift:Number(baselineDrift.toFixed(6)),passed,at:now()});const task=state.tasks.find(item=>item.id===mutation.taskId);if(!passed){mutation.status='rejected';if(task){task.status='open';task.claimedBy=null}}else if(mutation.verifications.filter(item=>item.passed).length>=2){mutation.status='accepted';mutation.acceptedAt=now();mutation.generation=state.lineage.length+1;if(task)task.status='complete';state.lineage.push({generation:mutation.generation,taskId:mutation.taskId,mutationId:mutation.id,baseCommit:mutation.baseCommit,artifact:mutation.patchDigest,gainPct:mutation.claimedGainPct,acceptedAt:mutation.acceptedAt,verifiers:mutation.verifications.map(item=>item.machineId)})}persistEvent(`mutation.${mutation.status}`,{mutation:cleanMutation(mutation)});return json(response,200,{mutation:cleanMutation(mutation)})}
if(path.startsWith('/api/'))return json(response,404,{error:'api route not found'});if(!staticFile(response,path))return json(response,404,{error:'not found'});
}catch(error){console.error(error);return json(response,error instanceof SyntaxError?400:500,{error:error.message||'internal server error'})}});
setInterval(()=>{for(const response of clients)response.write(`: keepalive ${Date.now()}\n\n`)},20000).unref();
server.listen(port,host,()=>console.log(`Veemo core listening on http://${host}:${port}`));