import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const port=4327,base=`http://127.0.0.1:${port}`,dataDir=mkdtempSync(join(tmpdir(),'veemo-test-'));
const child=spawn(process.execPath,['server.mjs'],{cwd:import.meta.dirname,env:{...process.env,PORT:String(port),VEEMO_DATA_DIR:dataDir},stdio:['ignore','pipe','pipe']});
async function wait(){for(let i=0;i<40;i++){try{if((await fetch(base+'/api/health')).ok)return}catch{}await new Promise(r=>setTimeout(r,100))}throw new Error('server did not start')}
async function call(path,method='GET',value,secret){const response=await fetch(base+path,{method,headers:{'content-type':'application/json',...(secret?{authorization:`Bearer ${secret}`}:{})},body:value?JSON.stringify(value):undefined}),result=await response.json();if(!response.ok)throw new Error(`${path}: ${response.status} ${JSON.stringify(result)}`);return result}
try{await wait();const task=(await call('/api/tasks','POST',{title:'Allocator hot path',repository:'https://github.com/example/runtime',baseCommit:'0123456789abcdef',target:'src/hot.rs',dockerImage:'rust:1.82-alpine',testCommand:['cargo','test','--locked'],benchmarkCommand:['./bench-json'],metric:'p95_ms',lowerIsBetter:true,minGainPct:2})).task;const workers=[];for(const name of ['author-01','verifier-01','verifier-02'])workers.push(await call('/api/machines/register','POST',{name,target:'rust',cpu:4,memoryGb:8}));await call(`/api/tasks/${task.id}/claim`,'POST',{},workers[0].secret);const patch='diff --git a/src/hot.rs b/src/hot.rs\n--- a/src/hot.rs\n+++ b/src/hot.rs\n@@ -1 +1 @@\n-old\n+new\n',patchDigest=createHash('sha256').update(patch).digest('hex');const submitted=await call('/api/mutations','POST',{taskId:task.id,patch,patchDigest,summary:'automated consensus test',baselineMetric:100,candidateMetric:90,testsPassed:true},workers[0].secret);await call(`/api/mutations/${submitted.mutation.id}/verify`,'POST',{observedBaselineMetric:101,observedMetric:91,testsPassed:true},workers[1].secret);const accepted=await call(`/api/mutations/${submitted.mutation.id}/verify`,'POST',{observedBaselineMetric:99.5,observedMetric:89.8,testsPassed:true},workers[2].secret);if(accepted.mutation.status!=='accepted'||accepted.mutation.generation!==1)throw new Error('mutation did not enter generation 1');const state=await call('/api/state');if(state.tasks[0].status!=='complete'||state.machines.length!==3||state.lineage.length!==1)throw new Error('state lifecycle mismatch');if((await fetch(base+'/data/state.json')).status!==404)throw new Error('private state is publicly readable');console.log('PASS: task lifecycle, claim, auth, patch hash, two-baseline consensus, persistence, static security')}finally{child.kill();await new Promise(resolve=>child.once('exit',resolve));rmSync(dataDir,{recursive:true,force:true})}